// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from 'dotenv'
import { join } from 'path'

// Try loading ../.env, and fallback to .env if needed
dotenv.config({ path: join(__dirname, '../.env') })
dotenv.config()

import { defineConfig } from 'prisma/config'

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
        seed: 'ts-node prisma/seed.ts',
    },
    datasource: {
        url: process.env['DATABASE_URL'],
    },
})
