import { Prisma } from '@prisma/client'

export const AUDIT_ENTITY_TYPES = {
    USER: 'USER',
    TRANSACTION: 'TRANSACTION',
    PAYMENT_SOURCE: 'PAYMENT_SOURCE',
    BUDGET: 'BUDGET',
    CATEGORY: 'CATEGORY',
    WORKSPACE: 'WORKSPACE',
    GOAL: 'GOAL',
    GOAL_OPERATION: 'GOAL_OPERATION',
} as const

export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES]

export const AUDIT_ACTIONS = {
    USER_REGISTERED: 'USER_REGISTERED',
    USER_EMAIL_VERIFIED: 'USER_EMAIL_VERIFIED',
    USER_EMAIL_VERIFICATION_RESENT: 'USER_EMAIL_VERIFICATION_RESENT',
    USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
    USER_PASSWORD_CHANGED: 'USER_PASSWORD_CHANGED',
    USER_2FA_ENABLED: 'USER_2FA_ENABLED',
    USER_2FA_DISABLED: 'USER_2FA_DISABLED',
    USER_DELETED: 'USER_DELETED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    TRANSACTION_CREATED: 'TRANSACTION_CREATED',
    TRANSACTION_UPDATED: 'TRANSACTION_UPDATED',
    TRANSACTION_DELETED: 'TRANSACTION_DELETED',
    PAYMENT_SOURCE_CREATED: 'PAYMENT_SOURCE_CREATED',
    PAYMENT_SOURCE_UPDATED: 'PAYMENT_SOURCE_UPDATED',
    PAYMENT_SOURCE_ARCHIVED: 'PAYMENT_SOURCE_ARCHIVED',
    BUDGET_CREATED: 'BUDGET_CREATED',
    BUDGET_UPDATED: 'BUDGET_UPDATED',
    BUDGET_DELETED: 'BUDGET_DELETED',
    CATEGORY_CREATED: 'CATEGORY_CREATED',
    CATEGORY_UPDATED: 'CATEGORY_UPDATED',
    CATEGORY_ARCHIVED: 'CATEGORY_ARCHIVED',
    CATEGORY_RESTORED: 'CATEGORY_RESTORED',
    CATEGORY_REORDERED: 'CATEGORY_REORDERED',
    WORKSPACE_UPDATED: 'WORKSPACE_UPDATED',
    GOAL_CREATED: 'GOAL_CREATED',
    GOAL_UPDATED: 'GOAL_UPDATED',
    GOAL_ARCHIVED: 'GOAL_ARCHIVED',
    GOAL_RESTORED: 'GOAL_RESTORED',
    GOAL_DELETED: 'GOAL_DELETED',
    GOAL_OPERATION_CREATED: 'GOAL_OPERATION_CREATED',
    GOAL_OPERATION_UPDATED: 'GOAL_OPERATION_UPDATED',
    GOAL_OPERATION_DELETED: 'GOAL_OPERATION_DELETED',
} as const

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS]

export type AuditMetadata = Prisma.InputJsonObject
