import { Prisma } from '@prisma/client'

export const AUDIT_ENTITY_TYPES = {
    USER: 'USER',
    TRANSACTION: 'TRANSACTION',
    PAYMENT_SOURCE: 'PAYMENT_SOURCE',
    BUDGET: 'BUDGET',
} as const

export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES]

export const AUDIT_ACTIONS = {
    USER_REGISTERED: 'USER_REGISTERED',
    USER_EMAIL_VERIFIED: 'USER_EMAIL_VERIFIED',
    USER_EMAIL_VERIFICATION_RESENT: 'USER_EMAIL_VERIFICATION_RESENT',
    USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
    USER_2FA_ENABLED: 'USER_2FA_ENABLED',
    USER_2FA_DISABLED: 'USER_2FA_DISABLED',
    USER_LOGGED_IN: 'USER_LOGGED_IN',
    USER_LOGGED_OUT: 'USER_LOGGED_OUT',
    TRANSACTION_CREATED: 'TRANSACTION_CREATED',
    TRANSACTION_DELETED: 'TRANSACTION_DELETED',
    PAYMENT_SOURCE_CREATED: 'PAYMENT_SOURCE_CREATED',
    PAYMENT_SOURCE_UPDATED: 'PAYMENT_SOURCE_UPDATED',
    PAYMENT_SOURCE_ARCHIVED: 'PAYMENT_SOURCE_ARCHIVED',
    BUDGET_CREATED: 'BUDGET_CREATED',
    BUDGET_UPDATED: 'BUDGET_UPDATED',
    BUDGET_DELETED: 'BUDGET_DELETED',
} as const

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS]

export type AuditMetadata = Prisma.InputJsonObject
