/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateGoalDto
 */
export interface CreateGoalDto {
  /**
   *
   * @type {string}
   * @memberof CreateGoalDto
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof CreateGoalDto
   */
  target_amount: number;
  /**
   *
   * @type {number}
   * @memberof CreateGoalDto
   */
  initial_amount?: number;
  /**
   *
   * @type {string}
   * @memberof CreateGoalDto
   */
  target_date: string;
  /**
   *
   * @type {boolean}
   * @memberof CreateGoalDto
   */
  include_current_month: boolean;
}
