/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CurrentPasswordDto
 */
export interface CurrentPasswordDto {
  /**
   *
   * @type {string}
   * @memberof CurrentPasswordDto
   */
  currentPassword: string;
}
