/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface GoalOperationDto
 */
export interface GoalOperationDto {
  /**
   *
   * @type {string}
   * @memberof GoalOperationDto
   */
  type: GoalOperationDtoTypeEnum;
  /**
   *
   * @type {number}
   * @memberof GoalOperationDto
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof GoalOperationDto
   */
  date: string;
  /**
   *
   * @type {string}
   * @memberof GoalOperationDto
   */
  note?: string;
}

export const GoalOperationDtoTypeEnum = {
  Deposit: "deposit",
  Withdrawal: "withdrawal",
} as const;

export type GoalOperationDtoTypeEnum =
  (typeof GoalOperationDtoTypeEnum)[keyof typeof GoalOperationDtoTypeEnum];
