/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

// May contain unused imports in some cases
// @ts-ignore
import { HealthControllerCheckHealth200ResponseInfoValue } from "./health-controller-check-health200-response-info-value";

/**
 *
 * @export
 * @interface HealthControllerCheckHealth200Response
 */
export interface HealthControllerCheckHealth200Response {
  /**
   *
   * @type {string}
   * @memberof HealthControllerCheckHealth200Response
   */
  status?: string;
  /**
   *
   * @type {{ [key: string]: HealthControllerCheckHealth200ResponseInfoValue; }}
   * @memberof HealthControllerCheckHealth200Response
   */
  info?: {
    [key: string]: HealthControllerCheckHealth200ResponseInfoValue;
  } | null;
  /**
   *
   * @type {{ [key: string]: HealthControllerCheckHealth200ResponseInfoValue; }}
   * @memberof HealthControllerCheckHealth200Response
   */
  error?: {
    [key: string]: HealthControllerCheckHealth200ResponseInfoValue;
  } | null;
  /**
   *
   * @type {{ [key: string]: HealthControllerCheckHealth200ResponseInfoValue; }}
   * @memberof HealthControllerCheckHealth200Response
   */
  details?: { [key: string]: HealthControllerCheckHealth200ResponseInfoValue };
}
