/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse20010Summary
 */
export interface InlineResponse20010Summary {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010Summary
   */
  month: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010Summary
   */
  currency: string;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20010Summary
   */
  current_total: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20010Summary
   */
  previous_total: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20010Summary
   */
  change_amount: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20010Summary
   */
  change_percentage: number | null;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010Summary
   */
  direction: InlineResponse20010SummaryDirectionEnum;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20010Summary
   */
  income_total: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20010Summary
   */
  net_total: number;
}

export const InlineResponse20010SummaryDirectionEnum = {
  Up: "up",
  Down: "down",
  Flat: "flat",
} as const;

export type InlineResponse20010SummaryDirectionEnum =
  (typeof InlineResponse20010SummaryDirectionEnum)[keyof typeof InlineResponse20010SummaryDirectionEnum];
