/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InlineResponse20010RecentTransactions } from "./inline-response20010-recent-transactions";

/**
 *
 * @export
 * @interface InlineResponse20011
 */
export interface InlineResponse20011 {
  /**
   *
   * @type {Array<InlineResponse20010RecentTransactions>}
   * @memberof InlineResponse20011
   */
  data: Array<InlineResponse20010RecentTransactions>;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20011
   */
  total: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20011
   */
  limit: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20011
   */
  offset: number;
}
