/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse2008
 */
export interface InlineResponse2008 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse2008
   */
  category_id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2008
   */
  category_name: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2008
   */
  category_system_key: string | null;
  /**
   *
   * @type {number}
   * @memberof InlineResponse2008
   */
  budget_amount: number | null;
  /**
   *
   * @type {number}
   * @memberof InlineResponse2008
   */
  limit: number | null;
  /**
   *
   * @type {number}
   * @memberof InlineResponse2008
   */
  spent: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse2008
   */
  remaining: number | null;
  /**
   *
   * @type {number}
   * @memberof InlineResponse2008
   */
  percentage: number | null;
}
