/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse20010CategoryBreakdownCategories
 */
export interface InlineResponse20010CategoryBreakdownCategories {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010CategoryBreakdownCategories
   */
  category_id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010CategoryBreakdownCategories
   */
  category_name: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010CategoryBreakdownCategories
   */
  category_system_key: string | null;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010CategoryBreakdownCategories
   */
  category_color: string | null;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20010CategoryBreakdownCategories
   */
  amount: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20010CategoryBreakdownCategories
   */
  percentage: number;
}
