/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse2009
 */
export interface InlineResponse2009 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse2009
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2009
   */
  workspace_id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2009
   */
  category_id: string | null;
  /**
   *
   * @type {number}
   * @memberof InlineResponse2009
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2009
   */
  currency: string;
  /**
   *
   * @type {number}
   * @memberof InlineResponse2009
   */
  year: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse2009
   */
  month: number;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2009
   */
  created_at: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse2009
   */
  updated_at: string;
}
