/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkspacesWorkspaceIdGoalsOperations } from "./workspaces-workspace-id-goals-operations";

/**
 *
 * @export
 * @interface InlineResponse20013
 */
export interface InlineResponse20013 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  workspace_id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  name: string;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20013
   */
  target_amount: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20013
   */
  initial_amount: number;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  currency: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  target_date: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  plan_start_month: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  archived_at: string | null;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20013
   */
  current_amount: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20013
   */
  remaining_amount: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20013
   */
  progress_percentage: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20013
   */
  remaining_months: number;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20013
   */
  recommended_monthly_amount: number | null;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  status: InlineResponse20013StatusEnum;
  /**
   *
   * @type {Array<WorkspacesWorkspaceIdGoalsOperations>}
   * @memberof InlineResponse20013
   */
  operations?: Array<WorkspacesWorkspaceIdGoalsOperations>;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  created_at: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20013
   */
  updated_at: string;
}

export const InlineResponse20013StatusEnum = {
  Active: "active",
  Completed: "completed",
  Overdue: "overdue",
} as const;

export type InlineResponse20013StatusEnum =
  (typeof InlineResponse20013StatusEnum)[keyof typeof InlineResponse20013StatusEnum];
