/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { InlineResponse20010CategoryBreakdownCategories } from "./inline-response20010-category-breakdown-categories";

/**
 *
 * @export
 * @interface InlineResponse20010CategoryBreakdown
 */
export interface InlineResponse20010CategoryBreakdown {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010CategoryBreakdown
   */
  month: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010CategoryBreakdown
   */
  currency: string;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20010CategoryBreakdown
   */
  total_spending: number;
  /**
   *
   * @type {Array<InlineResponse20010CategoryBreakdownCategories>}
   * @memberof InlineResponse20010CategoryBreakdown
   */
  categories: Array<InlineResponse20010CategoryBreakdownCategories>;
}
