/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse503
 */
export interface InlineResponse503 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse503
   */
  status?: string;
  /**
   *
   * @type {{ [key: string]: { [key: string]: object; }; }}
   * @memberof InlineResponse503
   */
  info?: { [key: string]: { [key: string]: object } } | null;
  /**
   *
   * @type {{ [key: string]: { [key: string]: object; }; }}
   * @memberof InlineResponse503
   */
  error?: { [key: string]: { [key: string]: object } } | null;
  /**
   *
   * @type {{ [key: string]: { [key: string]: object; }; }}
   * @memberof InlineResponse503
   */
  details?: { [key: string]: { [key: string]: object } };
}
