/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse20010RecentTransactions
 */
export interface InlineResponse20010RecentTransactions {
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  workspace_id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  category_id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  payment_source_id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  type: InlineResponse20010RecentTransactionsTypeEnum;
  /**
   *
   * @type {number}
   * @memberof InlineResponse20010RecentTransactions
   */
  amount: number;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  currency: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  date: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  description: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  notes: string | null;
  /**
   *
   * @type {Array<string>}
   * @memberof InlineResponse20010RecentTransactions
   */
  tags: Array<string>;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  created_at: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse20010RecentTransactions
   */
  updated_at: string;
}

export const InlineResponse20010RecentTransactionsTypeEnum = {
  Expense: "expense",
  Income: "income",
} as const;

export type InlineResponse20010RecentTransactionsTypeEnum =
  (typeof InlineResponse20010RecentTransactionsTypeEnum)[keyof typeof InlineResponse20010RecentTransactionsTypeEnum];
