/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface InlineResponse201
 */
export interface InlineResponse201 {
  /**
   *
   * @type {string}
   * @memberof InlineResponse201
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse201
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse201
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse201
   */
  locale: string;
  /**
   *
   * @type {boolean}
   * @memberof InlineResponse201
   */
  hideSalaryAmounts: boolean;
  /**
   *
   * @type {boolean}
   * @memberof InlineResponse201
   */
  emailVerified: boolean;
  /**
   *
   * @type {boolean}
   * @memberof InlineResponse201
   */
  totpEnabled: boolean;
  /**
   *
   * @type {string}
   * @memberof InlineResponse201
   */
  createdAt: string;
  /**
   *
   * @type {string}
   * @memberof InlineResponse201
   */
  updatedAt: string;
}
