/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface IntegrationCredentialResponseDto
 */
export interface IntegrationCredentialResponseDto {
  /**
   *
   * @type {string}
   * @memberof IntegrationCredentialResponseDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof IntegrationCredentialResponseDto
   */
  token_prefix: string;
  /**
   *
   * @type {string}
   * @memberof IntegrationCredentialResponseDto
   */
  status: string;
  /**
   *
   * @type {string}
   * @memberof IntegrationCredentialResponseDto
   */
  created_at: string;
  /**
   *
   * @type {string}
   * @memberof IntegrationCredentialResponseDto
   */
  expires_at: string;
  /**
   *
   * @type {object}
   * @memberof IntegrationCredentialResponseDto
   */
  revoked_at?: object | null;
  /**
   *
   * @type {object}
   * @memberof IntegrationCredentialResponseDto
   */
  last_used_at?: object | null;
  /**
   *
   * @type {Array<string>}
   * @memberof IntegrationCredentialResponseDto
   */
  scopes: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof IntegrationCredentialResponseDto
   */
  category_allowlist_enabled: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof IntegrationCredentialResponseDto
   */
  category_ids: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof IntegrationCredentialResponseDto
   */
  payment_source_allowlist_enabled: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof IntegrationCredentialResponseDto
   */
  payment_source_ids: Array<string>;
  /**
   *
   * @type {boolean}
   * @memberof IntegrationCredentialResponseDto
   */
  cidr_allowlist_enabled: boolean;
  /**
   *
   * @type {Array<string>}
   * @memberof IntegrationCredentialResponseDto
   */
  allowed_cidrs: Array<string>;
}
