/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PaymentSourceBodyDto
 */
export interface PaymentSourceBodyDto {
  /**
   *
   * @type {string}
   * @memberof PaymentSourceBodyDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof PaymentSourceBodyDto
   */
  type: PaymentSourceBodyDtoTypeEnum;
}

export const PaymentSourceBodyDtoTypeEnum = {
  Cash: "cash",
  DebitCard: "debit_card",
  CreditCard: "credit_card",
  Bank: "bank",
  Other: "other",
} as const;

export type PaymentSourceBodyDtoTypeEnum =
  (typeof PaymentSourceBodyDtoTypeEnum)[keyof typeof PaymentSourceBodyDtoTypeEnum];
