/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RegisterDto
 */
export interface RegisterDto {
  /**
   *
   * @type {string}
   * @memberof RegisterDto
   */
  email: string;
  /**
   *
   * @type {string}
   * @memberof RegisterDto
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof RegisterDto
   */
  password: string;
  /**
   *
   * @type {string}
   * @memberof RegisterDto
   */
  locale?: RegisterDtoLocaleEnum;
  /**
   *
   * @type {string}
   * @memberof RegisterDto
   */
  base_currency?: string;
  /**
   *
   * @type {string}
   * @memberof RegisterDto
   */
  turnstile_token?: string;
}

export const RegisterDtoLocaleEnum = {
  En: "en",
  Pl: "pl",
} as const;

export type RegisterDtoLocaleEnum =
  (typeof RegisterDtoLocaleEnum)[keyof typeof RegisterDtoLocaleEnum];
