/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RotateIntegrationCredentialDto
 */
export interface RotateIntegrationCredentialDto {
  /**
   *
   * @type {string}
   * @memberof RotateIntegrationCredentialDto
   */
  current_password: string;
  /**
   *
   * @type {string}
   * @memberof RotateIntegrationCredentialDto
   */
  two_factor_token?: string;
  /**
   *
   * @type {string}
   * @memberof RotateIntegrationCredentialDto
   */
  expires_at: string;
}
