/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface RotatedIntegrationCredentialResponseDto
 */
export interface RotatedIntegrationCredentialResponseDto {
  /**
   *
   * @type {string}
   * @memberof RotatedIntegrationCredentialResponseDto
   */
  credential_id: string;
  /**
   *
   * @type {string}
   * @memberof RotatedIntegrationCredentialResponseDto
   */
  token: string;
  /**
   *
   * @type {string}
   * @memberof RotatedIntegrationCredentialResponseDto
   */
  token_prefix: string;
  /**
   *
   * @type {string}
   * @memberof RotatedIntegrationCredentialResponseDto
   */
  expires_at: string;
}
