/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface UpdateUserProfileDto
 */
export interface UpdateUserProfileDto {
  /**
   *
   * @type {string}
   * @memberof UpdateUserProfileDto
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof UpdateUserProfileDto
   */
  locale?: UpdateUserProfileDtoLocaleEnum;
  /**
   *
   * @type {boolean}
   * @memberof UpdateUserProfileDto
   */
  hide_salary_amounts?: boolean;
}

export const UpdateUserProfileDtoLocaleEnum = {
  En: "en",
  Pl: "pl",
} as const;

export type UpdateUserProfileDtoLocaleEnum =
  (typeof UpdateUserProfileDtoLocaleEnum)[keyof typeof UpdateUserProfileDtoLocaleEnum];
