/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { WorkspacesWorkspaceIdCategoriesChildren } from "./workspaces-workspace-id-categories-children";

/**
 *
 * @export
 * @interface WorkspacesWorkspaceIdCategoriesChildren1
 */
export interface WorkspacesWorkspaceIdCategoriesChildren1 {
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren1
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren1
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren1
   */
  system_key: string | null;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren1
   */
  type: WorkspacesWorkspaceIdCategoriesChildren1TypeEnum;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren1
   */
  icon: string | null;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren1
   */
  parent_id: string | null;
  /**
   *
   * @type {number}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren1
   */
  sort_order: number;
  /**
   *
   * @type {boolean}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren1
   */
  is_archived: boolean;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren1
   */
  archived_at: string | null;
  /**
   *
   * @type {Array<WorkspacesWorkspaceIdCategoriesChildren>}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren1
   */
  children: Array<WorkspacesWorkspaceIdCategoriesChildren>;
}

export const WorkspacesWorkspaceIdCategoriesChildren1TypeEnum = {
  Expense: "expense",
  Income: "income",
} as const;

export type WorkspacesWorkspaceIdCategoriesChildren1TypeEnum =
  (typeof WorkspacesWorkspaceIdCategoriesChildren1TypeEnum)[keyof typeof WorkspacesWorkspaceIdCategoriesChildren1TypeEnum];
