/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WorkspacesWorkspaceIdCategoriesChildren
 */
export interface WorkspacesWorkspaceIdCategoriesChildren {
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren
   */
  system_key: string | null;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren
   */
  type: WorkspacesWorkspaceIdCategoriesChildrenTypeEnum;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren
   */
  icon: string | null;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren
   */
  parent_id: string | null;
  /**
   *
   * @type {number}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren
   */
  sort_order: number;
  /**
   *
   * @type {boolean}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren
   */
  is_archived: boolean;
  /**
   *
   * @type {string}
   * @memberof WorkspacesWorkspaceIdCategoriesChildren
   */
  archived_at: string | null;
}

export const WorkspacesWorkspaceIdCategoriesChildrenTypeEnum = {
  Expense: "expense",
  Income: "income",
} as const;

export type WorkspacesWorkspaceIdCategoriesChildrenTypeEnum =
  (typeof WorkspacesWorkspaceIdCategoriesChildrenTypeEnum)[keyof typeof WorkspacesWorkspaceIdCategoriesChildrenTypeEnum];
