/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, {
  type AxiosPromise,
  type AxiosInstance,
  type AxiosRequestConfig,
} from "axios";
import type { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import type { BudgetBodyDto } from "../model";
// @ts-ignore
import type { InlineResponse2008 } from "../model";
// @ts-ignore
import type { InlineResponse2009 } from "../model";
/**
 * BudgetsApi - axios parameter creator
 * @export
 */
export const BudgetsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {string} workspaceId
     * @param {BudgetBodyDto} budgetBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    budgetsControllerCreateBudget: async (
      workspaceId: string,
      budgetBodyDto: BudgetBodyDto,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "budgetsControllerCreateBudget",
        "workspaceId",
        workspaceId,
      );
      // verify required parameter 'budgetBodyDto' is not null or undefined
      assertParamExists(
        "budgetsControllerCreateBudget",
        "budgetBodyDto",
        budgetBodyDto,
      );
      const localVarPath = `/workspaces/{workspaceId}/budgets`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        budgetBodyDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    budgetsControllerDeleteBudget: async (
      id: string,
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("budgetsControllerDeleteBudget", "id", id);
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "budgetsControllerDeleteBudget",
        "workspaceId",
        workspaceId,
      );
      const localVarPath = `/workspaces/{workspaceId}/budgets/{id}`
        .replace(`{${"id"}}`, encodeURIComponent(String(id)))
        .replace(`{${"workspaceId"}}`, encodeURIComponent(String(workspaceId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    budgetsControllerListBudgetProgress: async (
      month: string,
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'month' is not null or undefined
      assertParamExists("budgetsControllerListBudgetProgress", "month", month);
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "budgetsControllerListBudgetProgress",
        "workspaceId",
        workspaceId,
      );
      const localVarPath = `/workspaces/{workspaceId}/budgets/progress`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (month !== undefined) {
        localVarQueryParameter["month"] = month;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {number} year
     * @param {number} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    budgetsControllerListBudgets: async (
      year: number,
      month: number,
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'year' is not null or undefined
      assertParamExists("budgetsControllerListBudgets", "year", year);
      // verify required parameter 'month' is not null or undefined
      assertParamExists("budgetsControllerListBudgets", "month", month);
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "budgetsControllerListBudgets",
        "workspaceId",
        workspaceId,
      );
      const localVarPath = `/workspaces/{workspaceId}/budgets`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (year !== undefined) {
        localVarQueryParameter["year"] = year;
      }

      if (month !== undefined) {
        localVarQueryParameter["month"] = month;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {BudgetBodyDto} budgetBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    budgetsControllerUpdateBudget: async (
      id: string,
      workspaceId: string,
      budgetBodyDto: BudgetBodyDto,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists("budgetsControllerUpdateBudget", "id", id);
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "budgetsControllerUpdateBudget",
        "workspaceId",
        workspaceId,
      );
      // verify required parameter 'budgetBodyDto' is not null or undefined
      assertParamExists(
        "budgetsControllerUpdateBudget",
        "budgetBodyDto",
        budgetBodyDto,
      );
      const localVarPath = `/workspaces/{workspaceId}/budgets/{id}`
        .replace(`{${"id"}}`, encodeURIComponent(String(id)))
        .replace(`{${"workspaceId"}}`, encodeURIComponent(String(workspaceId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        budgetBodyDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * BudgetsApi - functional programming interface
 * @export
 */
export const BudgetsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = BudgetsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {string} workspaceId
     * @param {BudgetBodyDto} budgetBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async budgetsControllerCreateBudget(
      workspaceId: string,
      budgetBodyDto: BudgetBodyDto,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse2009>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.budgetsControllerCreateBudget(
          workspaceId,
          budgetBodyDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async budgetsControllerDeleteBudget(
      id: string,
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.budgetsControllerDeleteBudget(
          id,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async budgetsControllerListBudgetProgress(
      month: string,
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<InlineResponse2008>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.budgetsControllerListBudgetProgress(
          month,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {number} year
     * @param {number} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async budgetsControllerListBudgets(
      year: number,
      month: number,
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<InlineResponse2009>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.budgetsControllerListBudgets(
          year,
          month,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {BudgetBodyDto} budgetBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async budgetsControllerUpdateBudget(
      id: string,
      workspaceId: string,
      budgetBodyDto: BudgetBodyDto,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse2009>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.budgetsControllerUpdateBudget(
          id,
          workspaceId,
          budgetBodyDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * BudgetsApi - factory interface
 * @export
 */
export const BudgetsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = BudgetsApiFp(configuration);
  return {
    /**
     *
     * @param {string} workspaceId
     * @param {BudgetBodyDto} budgetBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    budgetsControllerCreateBudget(
      workspaceId: string,
      budgetBodyDto: BudgetBodyDto,
      options?: any,
    ): AxiosPromise<InlineResponse2009> {
      return localVarFp
        .budgetsControllerCreateBudget(workspaceId, budgetBodyDto, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    budgetsControllerDeleteBudget(
      id: string,
      workspaceId: string,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .budgetsControllerDeleteBudget(id, workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    budgetsControllerListBudgetProgress(
      month: string,
      workspaceId: string,
      options?: any,
    ): AxiosPromise<Array<InlineResponse2008>> {
      return localVarFp
        .budgetsControllerListBudgetProgress(month, workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {number} year
     * @param {number} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    budgetsControllerListBudgets(
      year: number,
      month: number,
      workspaceId: string,
      options?: any,
    ): AxiosPromise<Array<InlineResponse2009>> {
      return localVarFp
        .budgetsControllerListBudgets(year, month, workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {BudgetBodyDto} budgetBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    budgetsControllerUpdateBudget(
      id: string,
      workspaceId: string,
      budgetBodyDto: BudgetBodyDto,
      options?: any,
    ): AxiosPromise<InlineResponse2009> {
      return localVarFp
        .budgetsControllerUpdateBudget(id, workspaceId, budgetBodyDto, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * BudgetsApi - object-oriented interface
 * @export
 * @class BudgetsApi
 * @extends {BaseAPI}
 */
export class BudgetsApi extends BaseAPI {
  /**
   *
   * @param {string} workspaceId
   * @param {BudgetBodyDto} budgetBodyDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetsApi
   */
  public budgetsControllerCreateBudget(
    workspaceId: string,
    budgetBodyDto: BudgetBodyDto,
    options?: AxiosRequestConfig,
  ) {
    return BudgetsApiFp(this.configuration)
      .budgetsControllerCreateBudget(workspaceId, budgetBodyDto, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} id
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetsApi
   */
  public budgetsControllerDeleteBudget(
    id: string,
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return BudgetsApiFp(this.configuration)
      .budgetsControllerDeleteBudget(id, workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} month
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetsApi
   */
  public budgetsControllerListBudgetProgress(
    month: string,
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return BudgetsApiFp(this.configuration)
      .budgetsControllerListBudgetProgress(month, workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {number} year
   * @param {number} month
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetsApi
   */
  public budgetsControllerListBudgets(
    year: number,
    month: number,
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return BudgetsApiFp(this.configuration)
      .budgetsControllerListBudgets(year, month, workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} id
   * @param {string} workspaceId
   * @param {BudgetBodyDto} budgetBodyDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof BudgetsApi
   */
  public budgetsControllerUpdateBudget(
    id: string,
    workspaceId: string,
    budgetBodyDto: BudgetBodyDto,
    options?: AxiosRequestConfig,
  ) {
    return BudgetsApiFp(this.configuration)
      .budgetsControllerUpdateBudget(id, workspaceId, budgetBodyDto, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
