/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, {
  type AxiosPromise,
  type AxiosInstance,
  type AxiosRequestConfig,
} from "axios";
import type { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import type { InlineResponse20010 } from "../model";
// @ts-ignore
import type { InlineResponse20010CategoryBreakdown } from "../model";
// @ts-ignore
import type { InlineResponse20010Summary } from "../model";
/**
 * DashboardApi - axios parameter creator
 * @export
 */
export const DashboardApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    dashboardControllerGetCategoryBreakdown: async (
      month: string,
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'month' is not null or undefined
      assertParamExists(
        "dashboardControllerGetCategoryBreakdown",
        "month",
        month,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "dashboardControllerGetCategoryBreakdown",
        "workspaceId",
        workspaceId,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/dashboard/category-breakdown`.replace(
          `{${"workspaceId"}}`,
          encodeURIComponent(String(workspaceId)),
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (month !== undefined) {
        localVarQueryParameter["month"] = month;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    dashboardControllerGetOverview: async (
      month: string,
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'month' is not null or undefined
      assertParamExists("dashboardControllerGetOverview", "month", month);
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "dashboardControllerGetOverview",
        "workspaceId",
        workspaceId,
      );
      const localVarPath = `/workspaces/{workspaceId}/dashboard`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (month !== undefined) {
        localVarQueryParameter["month"] = month;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    dashboardControllerGetSpendingSummary: async (
      month: string,
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'month' is not null or undefined
      assertParamExists(
        "dashboardControllerGetSpendingSummary",
        "month",
        month,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "dashboardControllerGetSpendingSummary",
        "workspaceId",
        workspaceId,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/dashboard/spending-summary`.replace(
          `{${"workspaceId"}}`,
          encodeURIComponent(String(workspaceId)),
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (month !== undefined) {
        localVarQueryParameter["month"] = month;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DashboardApi - functional programming interface
 * @export
 */
export const DashboardApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    DashboardApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async dashboardControllerGetCategoryBreakdown(
      month: string,
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse20010CategoryBreakdown>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.dashboardControllerGetCategoryBreakdown(
          month,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async dashboardControllerGetOverview(
      month: string,
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse20010>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.dashboardControllerGetOverview(
          month,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async dashboardControllerGetSpendingSummary(
      month: string,
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse20010Summary>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.dashboardControllerGetSpendingSummary(
          month,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * DashboardApi - factory interface
 * @export
 */
export const DashboardApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = DashboardApiFp(configuration);
  return {
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    dashboardControllerGetCategoryBreakdown(
      month: string,
      workspaceId: string,
      options?: any,
    ): AxiosPromise<InlineResponse20010CategoryBreakdown> {
      return localVarFp
        .dashboardControllerGetCategoryBreakdown(month, workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    dashboardControllerGetOverview(
      month: string,
      workspaceId: string,
      options?: any,
    ): AxiosPromise<InlineResponse20010> {
      return localVarFp
        .dashboardControllerGetOverview(month, workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} month
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    dashboardControllerGetSpendingSummary(
      month: string,
      workspaceId: string,
      options?: any,
    ): AxiosPromise<InlineResponse20010Summary> {
      return localVarFp
        .dashboardControllerGetSpendingSummary(month, workspaceId, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * DashboardApi - object-oriented interface
 * @export
 * @class DashboardApi
 * @extends {BaseAPI}
 */
export class DashboardApi extends BaseAPI {
  /**
   *
   * @param {string} month
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DashboardApi
   */
  public dashboardControllerGetCategoryBreakdown(
    month: string,
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return DashboardApiFp(this.configuration)
      .dashboardControllerGetCategoryBreakdown(month, workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} month
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DashboardApi
   */
  public dashboardControllerGetOverview(
    month: string,
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return DashboardApiFp(this.configuration)
      .dashboardControllerGetOverview(month, workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} month
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DashboardApi
   */
  public dashboardControllerGetSpendingSummary(
    month: string,
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return DashboardApiFp(this.configuration)
      .dashboardControllerGetSpendingSummary(month, workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
