/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, {
  type AxiosPromise,
  type AxiosInstance,
  type AxiosRequestConfig,
} from "axios";
import type { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
/**
 * ExportApi - axios parameter creator
 * @export
 */
export const ExportApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {'csv' | 'json'} format
     * @param {string} workspaceId
     * @param {string} [dateFrom]
     * @param {string} [dateTo]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportControllerExportTransactions: async (
      format: "csv" | "json",
      workspaceId: string,
      dateFrom?: string,
      dateTo?: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'format' is not null or undefined
      assertParamExists("exportControllerExportTransactions", "format", format);
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "exportControllerExportTransactions",
        "workspaceId",
        workspaceId,
      );
      const localVarPath = `/workspaces/{workspaceId}/export`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (format !== undefined) {
        localVarQueryParameter["format"] = format;
      }

      if (dateFrom !== undefined) {
        localVarQueryParameter["date_from"] =
          (dateFrom as any) instanceof Date
            ? (dateFrom as any).toISOString().substr(0, 10)
            : dateFrom;
      }

      if (dateTo !== undefined) {
        localVarQueryParameter["date_to"] =
          (dateTo as any) instanceof Date
            ? (dateTo as any).toISOString().substr(0, 10)
            : dateTo;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ExportApi - functional programming interface
 * @export
 */
export const ExportApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = ExportApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {'csv' | 'json'} format
     * @param {string} workspaceId
     * @param {string} [dateFrom]
     * @param {string} [dateTo]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async exportControllerExportTransactions(
      format: "csv" | "json",
      workspaceId: string,
      dateFrom?: string,
      dateTo?: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.exportControllerExportTransactions(
          format,
          workspaceId,
          dateFrom,
          dateTo,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * ExportApi - factory interface
 * @export
 */
export const ExportApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ExportApiFp(configuration);
  return {
    /**
     *
     * @param {'csv' | 'json'} format
     * @param {string} workspaceId
     * @param {string} [dateFrom]
     * @param {string} [dateTo]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportControllerExportTransactions(
      format: "csv" | "json",
      workspaceId: string,
      dateFrom?: string,
      dateTo?: string,
      options?: any,
    ): AxiosPromise<any> {
      return localVarFp
        .exportControllerExportTransactions(
          format,
          workspaceId,
          dateFrom,
          dateTo,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ExportApi - object-oriented interface
 * @export
 * @class ExportApi
 * @extends {BaseAPI}
 */
export class ExportApi extends BaseAPI {
  /**
   *
   * @param {'csv' | 'json'} format
   * @param {string} workspaceId
   * @param {string} [dateFrom]
   * @param {string} [dateTo]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ExportApi
   */
  public exportControllerExportTransactions(
    format: "csv" | "json",
    workspaceId: string,
    dateFrom?: string,
    dateTo?: string,
    options?: AxiosRequestConfig,
  ) {
    return ExportApiFp(this.configuration)
      .exportControllerExportTransactions(
        format,
        workspaceId,
        dateFrom,
        dateTo,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
