/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, {
  type AxiosPromise,
  type AxiosInstance,
  type AxiosRequestConfig,
} from "axios";
import type { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import type { ExternalTransactionBodyDto } from "../model";
/**
 * ExternalTransactionsApi - axios parameter creator
 * @export
 */
export const ExternalTransactionsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerCategories: async (
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerCategories",
        "workspaceId",
        workspaceId,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/external-categories`.replace(
          `{${"workspaceId"}}`,
          encodeURIComponent(String(workspaceId)),
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} idempotencyKey
     * @param {string} idempotencyKey2
     * @param {string} workspaceId
     * @param {ExternalTransactionBodyDto} externalTransactionBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerCreate: async (
      idempotencyKey: string,
      idempotencyKey2: string,
      workspaceId: string,
      externalTransactionBodyDto: ExternalTransactionBodyDto,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'idempotencyKey' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerCreate",
        "idempotencyKey",
        idempotencyKey,
      );
      // verify required parameter 'idempotencyKey2' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerCreate",
        "idempotencyKey2",
        idempotencyKey2,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerCreate",
        "workspaceId",
        workspaceId,
      );
      // verify required parameter 'externalTransactionBodyDto' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerCreate",
        "externalTransactionBodyDto",
        externalTransactionBodyDto,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/external-transactions`.replace(
          `{${"workspaceId"}}`,
          encodeURIComponent(String(workspaceId)),
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (idempotencyKey !== undefined && idempotencyKey !== null) {
        localVarHeaderParameter["idempotency-key"] = String(idempotencyKey);
      }

      if (idempotencyKey2 !== undefined && idempotencyKey2 !== null) {
        localVarHeaderParameter["Idempotency-Key"] = String(idempotencyKey2);
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        externalTransactionBodyDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} externalId
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerGet: async (
      externalId: string,
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'externalId' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerGet",
        "externalId",
        externalId,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerGet",
        "workspaceId",
        workspaceId,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/external-transactions/{externalId}`
          .replace(`{${"externalId"}}`, encodeURIComponent(String(externalId)))
          .replace(
            `{${"workspaceId"}}`,
            encodeURIComponent(String(workspaceId)),
          );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerPaymentSources: async (
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerPaymentSources",
        "workspaceId",
        workspaceId,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/external-payment-sources`.replace(
          `{${"workspaceId"}}`,
          encodeURIComponent(String(workspaceId)),
        );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} externalId
     * @param {string} idempotencyKey
     * @param {string} ifMatch
     * @param {string} idempotencyKey2
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerRemove: async (
      externalId: string,
      idempotencyKey: string,
      ifMatch: string,
      idempotencyKey2: string,
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'externalId' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerRemove",
        "externalId",
        externalId,
      );
      // verify required parameter 'idempotencyKey' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerRemove",
        "idempotencyKey",
        idempotencyKey,
      );
      // verify required parameter 'ifMatch' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerRemove",
        "ifMatch",
        ifMatch,
      );
      // verify required parameter 'idempotencyKey2' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerRemove",
        "idempotencyKey2",
        idempotencyKey2,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerRemove",
        "workspaceId",
        workspaceId,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/external-transactions/{externalId}`
          .replace(`{${"externalId"}}`, encodeURIComponent(String(externalId)))
          .replace(
            `{${"workspaceId"}}`,
            encodeURIComponent(String(workspaceId)),
          );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (idempotencyKey !== undefined && idempotencyKey !== null) {
        localVarHeaderParameter["idempotency-key"] = String(idempotencyKey);
      }

      if (ifMatch !== undefined && ifMatch !== null) {
        localVarHeaderParameter["If-Match"] = String(ifMatch);
      }

      if (idempotencyKey2 !== undefined && idempotencyKey2 !== null) {
        localVarHeaderParameter["Idempotency-Key"] = String(idempotencyKey2);
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} externalId
     * @param {string} idempotencyKey
     * @param {string} ifMatch
     * @param {string} idempotencyKey2
     * @param {string} workspaceId
     * @param {ExternalTransactionBodyDto} externalTransactionBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerUpdate: async (
      externalId: string,
      idempotencyKey: string,
      ifMatch: string,
      idempotencyKey2: string,
      workspaceId: string,
      externalTransactionBodyDto: ExternalTransactionBodyDto,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'externalId' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerUpdate",
        "externalId",
        externalId,
      );
      // verify required parameter 'idempotencyKey' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerUpdate",
        "idempotencyKey",
        idempotencyKey,
      );
      // verify required parameter 'ifMatch' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerUpdate",
        "ifMatch",
        ifMatch,
      );
      // verify required parameter 'idempotencyKey2' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerUpdate",
        "idempotencyKey2",
        idempotencyKey2,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerUpdate",
        "workspaceId",
        workspaceId,
      );
      // verify required parameter 'externalTransactionBodyDto' is not null or undefined
      assertParamExists(
        "externalTransactionsControllerUpdate",
        "externalTransactionBodyDto",
        externalTransactionBodyDto,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/external-transactions/{externalId}`
          .replace(`{${"externalId"}}`, encodeURIComponent(String(externalId)))
          .replace(
            `{${"workspaceId"}}`,
            encodeURIComponent(String(workspaceId)),
          );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (idempotencyKey !== undefined && idempotencyKey !== null) {
        localVarHeaderParameter["idempotency-key"] = String(idempotencyKey);
      }

      if (ifMatch !== undefined && ifMatch !== null) {
        localVarHeaderParameter["If-Match"] = String(ifMatch);
      }

      if (idempotencyKey2 !== undefined && idempotencyKey2 !== null) {
        localVarHeaderParameter["Idempotency-Key"] = String(idempotencyKey2);
      }

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        externalTransactionBodyDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * ExternalTransactionsApi - functional programming interface
 * @export
 */
export const ExternalTransactionsApiFp = function (
  configuration?: Configuration,
) {
  const localVarAxiosParamCreator =
    ExternalTransactionsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async externalTransactionsControllerCategories(
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.externalTransactionsControllerCategories(
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} idempotencyKey
     * @param {string} idempotencyKey2
     * @param {string} workspaceId
     * @param {ExternalTransactionBodyDto} externalTransactionBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async externalTransactionsControllerCreate(
      idempotencyKey: string,
      idempotencyKey2: string,
      workspaceId: string,
      externalTransactionBodyDto: ExternalTransactionBodyDto,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.externalTransactionsControllerCreate(
          idempotencyKey,
          idempotencyKey2,
          workspaceId,
          externalTransactionBodyDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} externalId
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async externalTransactionsControllerGet(
      externalId: string,
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.externalTransactionsControllerGet(
          externalId,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async externalTransactionsControllerPaymentSources(
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.externalTransactionsControllerPaymentSources(
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} externalId
     * @param {string} idempotencyKey
     * @param {string} ifMatch
     * @param {string} idempotencyKey2
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async externalTransactionsControllerRemove(
      externalId: string,
      idempotencyKey: string,
      ifMatch: string,
      idempotencyKey2: string,
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.externalTransactionsControllerRemove(
          externalId,
          idempotencyKey,
          ifMatch,
          idempotencyKey2,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} externalId
     * @param {string} idempotencyKey
     * @param {string} ifMatch
     * @param {string} idempotencyKey2
     * @param {string} workspaceId
     * @param {ExternalTransactionBodyDto} externalTransactionBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async externalTransactionsControllerUpdate(
      externalId: string,
      idempotencyKey: string,
      ifMatch: string,
      idempotencyKey2: string,
      workspaceId: string,
      externalTransactionBodyDto: ExternalTransactionBodyDto,
      options?: AxiosRequestConfig,
    ): Promise<
      (axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.externalTransactionsControllerUpdate(
          externalId,
          idempotencyKey,
          ifMatch,
          idempotencyKey2,
          workspaceId,
          externalTransactionBodyDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * ExternalTransactionsApi - factory interface
 * @export
 */
export const ExternalTransactionsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = ExternalTransactionsApiFp(configuration);
  return {
    /**
     *
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerCategories(
      workspaceId: string,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .externalTransactionsControllerCategories(workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} idempotencyKey
     * @param {string} idempotencyKey2
     * @param {string} workspaceId
     * @param {ExternalTransactionBodyDto} externalTransactionBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerCreate(
      idempotencyKey: string,
      idempotencyKey2: string,
      workspaceId: string,
      externalTransactionBodyDto: ExternalTransactionBodyDto,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .externalTransactionsControllerCreate(
          idempotencyKey,
          idempotencyKey2,
          workspaceId,
          externalTransactionBodyDto,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} externalId
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerGet(
      externalId: string,
      workspaceId: string,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .externalTransactionsControllerGet(externalId, workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerPaymentSources(
      workspaceId: string,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .externalTransactionsControllerPaymentSources(workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} externalId
     * @param {string} idempotencyKey
     * @param {string} ifMatch
     * @param {string} idempotencyKey2
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerRemove(
      externalId: string,
      idempotencyKey: string,
      ifMatch: string,
      idempotencyKey2: string,
      workspaceId: string,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .externalTransactionsControllerRemove(
          externalId,
          idempotencyKey,
          ifMatch,
          idempotencyKey2,
          workspaceId,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} externalId
     * @param {string} idempotencyKey
     * @param {string} ifMatch
     * @param {string} idempotencyKey2
     * @param {string} workspaceId
     * @param {ExternalTransactionBodyDto} externalTransactionBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    externalTransactionsControllerUpdate(
      externalId: string,
      idempotencyKey: string,
      ifMatch: string,
      idempotencyKey2: string,
      workspaceId: string,
      externalTransactionBodyDto: ExternalTransactionBodyDto,
      options?: any,
    ): AxiosPromise<void> {
      return localVarFp
        .externalTransactionsControllerUpdate(
          externalId,
          idempotencyKey,
          ifMatch,
          idempotencyKey2,
          workspaceId,
          externalTransactionBodyDto,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * ExternalTransactionsApi - object-oriented interface
 * @export
 * @class ExternalTransactionsApi
 * @extends {BaseAPI}
 */
export class ExternalTransactionsApi extends BaseAPI {
  /**
   *
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ExternalTransactionsApi
   */
  public externalTransactionsControllerCategories(
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return ExternalTransactionsApiFp(this.configuration)
      .externalTransactionsControllerCategories(workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} idempotencyKey
   * @param {string} idempotencyKey2
   * @param {string} workspaceId
   * @param {ExternalTransactionBodyDto} externalTransactionBodyDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ExternalTransactionsApi
   */
  public externalTransactionsControllerCreate(
    idempotencyKey: string,
    idempotencyKey2: string,
    workspaceId: string,
    externalTransactionBodyDto: ExternalTransactionBodyDto,
    options?: AxiosRequestConfig,
  ) {
    return ExternalTransactionsApiFp(this.configuration)
      .externalTransactionsControllerCreate(
        idempotencyKey,
        idempotencyKey2,
        workspaceId,
        externalTransactionBodyDto,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} externalId
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ExternalTransactionsApi
   */
  public externalTransactionsControllerGet(
    externalId: string,
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return ExternalTransactionsApiFp(this.configuration)
      .externalTransactionsControllerGet(externalId, workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ExternalTransactionsApi
   */
  public externalTransactionsControllerPaymentSources(
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return ExternalTransactionsApiFp(this.configuration)
      .externalTransactionsControllerPaymentSources(workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} externalId
   * @param {string} idempotencyKey
   * @param {string} ifMatch
   * @param {string} idempotencyKey2
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ExternalTransactionsApi
   */
  public externalTransactionsControllerRemove(
    externalId: string,
    idempotencyKey: string,
    ifMatch: string,
    idempotencyKey2: string,
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return ExternalTransactionsApiFp(this.configuration)
      .externalTransactionsControllerRemove(
        externalId,
        idempotencyKey,
        ifMatch,
        idempotencyKey2,
        workspaceId,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} externalId
   * @param {string} idempotencyKey
   * @param {string} ifMatch
   * @param {string} idempotencyKey2
   * @param {string} workspaceId
   * @param {ExternalTransactionBodyDto} externalTransactionBodyDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ExternalTransactionsApi
   */
  public externalTransactionsControllerUpdate(
    externalId: string,
    idempotencyKey: string,
    ifMatch: string,
    idempotencyKey2: string,
    workspaceId: string,
    externalTransactionBodyDto: ExternalTransactionBodyDto,
    options?: AxiosRequestConfig,
  ) {
    return ExternalTransactionsApiFp(this.configuration)
      .externalTransactionsControllerUpdate(
        externalId,
        idempotencyKey,
        ifMatch,
        idempotencyKey2,
        workspaceId,
        externalTransactionBodyDto,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
