/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, {
  type AxiosPromise,
  type AxiosInstance,
  type AxiosRequestConfig,
} from "axios";
import type { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import type { CreateIntegrationCredentialDto } from "../model";
// @ts-ignore
import type { CredentialStepUpDto } from "../model";
// @ts-ignore
import type { DeletedIntegrationCredentialResponseDto } from "../model";
// @ts-ignore
import type { IntegrationResponseDto } from "../model";
// @ts-ignore
import type { IssuedIntegrationCredentialResponseDto } from "../model";
// @ts-ignore
import type { RevokedIntegrationCredentialResponseDto } from "../model";
// @ts-ignore
import type { RotateIntegrationCredentialDto } from "../model";
// @ts-ignore
import type { RotatedIntegrationCredentialResponseDto } from "../model";
/**
 * IntegrationsApi - axios parameter creator
 * @export
 */
export const IntegrationsApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {any} workspaceId
     * @param {CreateIntegrationCredentialDto} createIntegrationCredentialDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerCreate: async (
      workspaceId: any,
      createIntegrationCredentialDto: CreateIntegrationCredentialDto,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerCreate",
        "workspaceId",
        workspaceId,
      );
      // verify required parameter 'createIntegrationCredentialDto' is not null or undefined
      assertParamExists(
        "integrationManagementControllerCreate",
        "createIntegrationCredentialDto",
        createIntegrationCredentialDto,
      );
      const localVarPath = `/workspaces/{workspaceId}/integrations`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        createIntegrationCredentialDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} integrationId
     * @param {any} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerGet: async (
      integrationId: string,
      workspaceId: any,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'integrationId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerGet",
        "integrationId",
        integrationId,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerGet",
        "workspaceId",
        workspaceId,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/integrations/{integrationId}`
          .replace(
            `{${"integrationId"}}`,
            encodeURIComponent(String(integrationId)),
          )
          .replace(
            `{${"workspaceId"}}`,
            encodeURIComponent(String(workspaceId)),
          );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {any} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerList: async (
      workspaceId: any,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerList",
        "workspaceId",
        workspaceId,
      );
      const localVarPath = `/workspaces/{workspaceId}/integrations`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} integrationId
     * @param {string} credentialId
     * @param {any} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerRemove: async (
      integrationId: string,
      credentialId: string,
      workspaceId: any,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'integrationId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRemove",
        "integrationId",
        integrationId,
      );
      // verify required parameter 'credentialId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRemove",
        "credentialId",
        credentialId,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRemove",
        "workspaceId",
        workspaceId,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/integrations/{integrationId}/credentials/{credentialId}`
          .replace(
            `{${"integrationId"}}`,
            encodeURIComponent(String(integrationId)),
          )
          .replace(
            `{${"credentialId"}}`,
            encodeURIComponent(String(credentialId)),
          )
          .replace(
            `{${"workspaceId"}}`,
            encodeURIComponent(String(workspaceId)),
          );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "DELETE",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} integrationId
     * @param {string} credentialId
     * @param {any} workspaceId
     * @param {CredentialStepUpDto} credentialStepUpDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerRevoke: async (
      integrationId: string,
      credentialId: string,
      workspaceId: any,
      credentialStepUpDto: CredentialStepUpDto,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'integrationId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRevoke",
        "integrationId",
        integrationId,
      );
      // verify required parameter 'credentialId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRevoke",
        "credentialId",
        credentialId,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRevoke",
        "workspaceId",
        workspaceId,
      );
      // verify required parameter 'credentialStepUpDto' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRevoke",
        "credentialStepUpDto",
        credentialStepUpDto,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/integrations/{integrationId}/credentials/{credentialId}/revoke`
          .replace(
            `{${"integrationId"}}`,
            encodeURIComponent(String(integrationId)),
          )
          .replace(
            `{${"credentialId"}}`,
            encodeURIComponent(String(credentialId)),
          )
          .replace(
            `{${"workspaceId"}}`,
            encodeURIComponent(String(workspaceId)),
          );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        credentialStepUpDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} integrationId
     * @param {string} credentialId
     * @param {any} workspaceId
     * @param {RotateIntegrationCredentialDto} rotateIntegrationCredentialDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerRotate: async (
      integrationId: string,
      credentialId: string,
      workspaceId: any,
      rotateIntegrationCredentialDto: RotateIntegrationCredentialDto,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'integrationId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRotate",
        "integrationId",
        integrationId,
      );
      // verify required parameter 'credentialId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRotate",
        "credentialId",
        credentialId,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRotate",
        "workspaceId",
        workspaceId,
      );
      // verify required parameter 'rotateIntegrationCredentialDto' is not null or undefined
      assertParamExists(
        "integrationManagementControllerRotate",
        "rotateIntegrationCredentialDto",
        rotateIntegrationCredentialDto,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/integrations/{integrationId}/credentials/{credentialId}/rotate`
          .replace(
            `{${"integrationId"}}`,
            encodeURIComponent(String(integrationId)),
          )
          .replace(
            `{${"credentialId"}}`,
            encodeURIComponent(String(credentialId)),
          )
          .replace(
            `{${"workspaceId"}}`,
            encodeURIComponent(String(workspaceId)),
          );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        rotateIntegrationCredentialDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * IntegrationsApi - functional programming interface
 * @export
 */
export const IntegrationsApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    IntegrationsApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {any} workspaceId
     * @param {CreateIntegrationCredentialDto} createIntegrationCredentialDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async integrationManagementControllerCreate(
      workspaceId: any,
      createIntegrationCredentialDto: CreateIntegrationCredentialDto,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<IssuedIntegrationCredentialResponseDto>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.integrationManagementControllerCreate(
          workspaceId,
          createIntegrationCredentialDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} integrationId
     * @param {any} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async integrationManagementControllerGet(
      integrationId: string,
      workspaceId: any,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<IntegrationResponseDto>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.integrationManagementControllerGet(
          integrationId,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {any} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async integrationManagementControllerList(
      workspaceId: any,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<IntegrationResponseDto>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.integrationManagementControllerList(
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} integrationId
     * @param {string} credentialId
     * @param {any} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async integrationManagementControllerRemove(
      integrationId: string,
      credentialId: string,
      workspaceId: any,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<DeletedIntegrationCredentialResponseDto>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.integrationManagementControllerRemove(
          integrationId,
          credentialId,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} integrationId
     * @param {string} credentialId
     * @param {any} workspaceId
     * @param {CredentialStepUpDto} credentialStepUpDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async integrationManagementControllerRevoke(
      integrationId: string,
      credentialId: string,
      workspaceId: any,
      credentialStepUpDto: CredentialStepUpDto,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<RevokedIntegrationCredentialResponseDto>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.integrationManagementControllerRevoke(
          integrationId,
          credentialId,
          workspaceId,
          credentialStepUpDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} integrationId
     * @param {string} credentialId
     * @param {any} workspaceId
     * @param {RotateIntegrationCredentialDto} rotateIntegrationCredentialDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async integrationManagementControllerRotate(
      integrationId: string,
      credentialId: string,
      workspaceId: any,
      rotateIntegrationCredentialDto: RotateIntegrationCredentialDto,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<RotatedIntegrationCredentialResponseDto>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.integrationManagementControllerRotate(
          integrationId,
          credentialId,
          workspaceId,
          rotateIntegrationCredentialDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * IntegrationsApi - factory interface
 * @export
 */
export const IntegrationsApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = IntegrationsApiFp(configuration);
  return {
    /**
     *
     * @param {any} workspaceId
     * @param {CreateIntegrationCredentialDto} createIntegrationCredentialDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerCreate(
      workspaceId: any,
      createIntegrationCredentialDto: CreateIntegrationCredentialDto,
      options?: any,
    ): AxiosPromise<IssuedIntegrationCredentialResponseDto> {
      return localVarFp
        .integrationManagementControllerCreate(
          workspaceId,
          createIntegrationCredentialDto,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} integrationId
     * @param {any} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerGet(
      integrationId: string,
      workspaceId: any,
      options?: any,
    ): AxiosPromise<IntegrationResponseDto> {
      return localVarFp
        .integrationManagementControllerGet(integrationId, workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {any} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerList(
      workspaceId: any,
      options?: any,
    ): AxiosPromise<Array<IntegrationResponseDto>> {
      return localVarFp
        .integrationManagementControllerList(workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} integrationId
     * @param {string} credentialId
     * @param {any} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerRemove(
      integrationId: string,
      credentialId: string,
      workspaceId: any,
      options?: any,
    ): AxiosPromise<DeletedIntegrationCredentialResponseDto> {
      return localVarFp
        .integrationManagementControllerRemove(
          integrationId,
          credentialId,
          workspaceId,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} integrationId
     * @param {string} credentialId
     * @param {any} workspaceId
     * @param {CredentialStepUpDto} credentialStepUpDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerRevoke(
      integrationId: string,
      credentialId: string,
      workspaceId: any,
      credentialStepUpDto: CredentialStepUpDto,
      options?: any,
    ): AxiosPromise<RevokedIntegrationCredentialResponseDto> {
      return localVarFp
        .integrationManagementControllerRevoke(
          integrationId,
          credentialId,
          workspaceId,
          credentialStepUpDto,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} integrationId
     * @param {string} credentialId
     * @param {any} workspaceId
     * @param {RotateIntegrationCredentialDto} rotateIntegrationCredentialDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    integrationManagementControllerRotate(
      integrationId: string,
      credentialId: string,
      workspaceId: any,
      rotateIntegrationCredentialDto: RotateIntegrationCredentialDto,
      options?: any,
    ): AxiosPromise<RotatedIntegrationCredentialResponseDto> {
      return localVarFp
        .integrationManagementControllerRotate(
          integrationId,
          credentialId,
          workspaceId,
          rotateIntegrationCredentialDto,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * IntegrationsApi - object-oriented interface
 * @export
 * @class IntegrationsApi
 * @extends {BaseAPI}
 */
export class IntegrationsApi extends BaseAPI {
  /**
   *
   * @param {any} workspaceId
   * @param {CreateIntegrationCredentialDto} createIntegrationCredentialDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IntegrationsApi
   */
  public integrationManagementControllerCreate(
    workspaceId: any,
    createIntegrationCredentialDto: CreateIntegrationCredentialDto,
    options?: AxiosRequestConfig,
  ) {
    return IntegrationsApiFp(this.configuration)
      .integrationManagementControllerCreate(
        workspaceId,
        createIntegrationCredentialDto,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} integrationId
   * @param {any} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IntegrationsApi
   */
  public integrationManagementControllerGet(
    integrationId: string,
    workspaceId: any,
    options?: AxiosRequestConfig,
  ) {
    return IntegrationsApiFp(this.configuration)
      .integrationManagementControllerGet(integrationId, workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {any} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IntegrationsApi
   */
  public integrationManagementControllerList(
    workspaceId: any,
    options?: AxiosRequestConfig,
  ) {
    return IntegrationsApiFp(this.configuration)
      .integrationManagementControllerList(workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} integrationId
   * @param {string} credentialId
   * @param {any} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IntegrationsApi
   */
  public integrationManagementControllerRemove(
    integrationId: string,
    credentialId: string,
    workspaceId: any,
    options?: AxiosRequestConfig,
  ) {
    return IntegrationsApiFp(this.configuration)
      .integrationManagementControllerRemove(
        integrationId,
        credentialId,
        workspaceId,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} integrationId
   * @param {string} credentialId
   * @param {any} workspaceId
   * @param {CredentialStepUpDto} credentialStepUpDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IntegrationsApi
   */
  public integrationManagementControllerRevoke(
    integrationId: string,
    credentialId: string,
    workspaceId: any,
    credentialStepUpDto: CredentialStepUpDto,
    options?: AxiosRequestConfig,
  ) {
    return IntegrationsApiFp(this.configuration)
      .integrationManagementControllerRevoke(
        integrationId,
        credentialId,
        workspaceId,
        credentialStepUpDto,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} integrationId
   * @param {string} credentialId
   * @param {any} workspaceId
   * @param {RotateIntegrationCredentialDto} rotateIntegrationCredentialDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof IntegrationsApi
   */
  public integrationManagementControllerRotate(
    integrationId: string,
    credentialId: string,
    workspaceId: any,
    rotateIntegrationCredentialDto: RotateIntegrationCredentialDto,
    options?: AxiosRequestConfig,
  ) {
    return IntegrationsApiFp(this.configuration)
      .integrationManagementControllerRotate(
        integrationId,
        credentialId,
        workspaceId,
        rotateIntegrationCredentialDto,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
