/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, {
  type AxiosPromise,
  type AxiosInstance,
  type AxiosRequestConfig,
} from "axios";
import type { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import type { InlineResponse20012 } from "../model";
// @ts-ignore
import type { PaymentSourceBodyDto } from "../model";
/**
 * PaymentSourcesApi - axios parameter creator
 * @export
 */
export const PaymentSourcesApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentSourcesControllerArchivePaymentSource: async (
      id: string,
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists(
        "paymentSourcesControllerArchivePaymentSource",
        "id",
        id,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "paymentSourcesControllerArchivePaymentSource",
        "workspaceId",
        workspaceId,
      );
      const localVarPath =
        `/workspaces/{workspaceId}/payment-sources/{id}/archive`
          .replace(`{${"id"}}`, encodeURIComponent(String(id)))
          .replace(
            `{${"workspaceId"}}`,
            encodeURIComponent(String(workspaceId)),
          );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} workspaceId
     * @param {PaymentSourceBodyDto} paymentSourceBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentSourcesControllerCreatePaymentSource: async (
      workspaceId: string,
      paymentSourceBodyDto: PaymentSourceBodyDto,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "paymentSourcesControllerCreatePaymentSource",
        "workspaceId",
        workspaceId,
      );
      // verify required parameter 'paymentSourceBodyDto' is not null or undefined
      assertParamExists(
        "paymentSourcesControllerCreatePaymentSource",
        "paymentSourceBodyDto",
        paymentSourceBodyDto,
      );
      const localVarPath = `/workspaces/{workspaceId}/payment-sources`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "POST",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        paymentSourceBodyDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} workspaceId
     * @param {boolean} [includeArchived]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentSourcesControllerListPaymentSources: async (
      workspaceId: string,
      includeArchived?: boolean,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "paymentSourcesControllerListPaymentSources",
        "workspaceId",
        workspaceId,
      );
      const localVarPath = `/workspaces/{workspaceId}/payment-sources`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      if (includeArchived !== undefined) {
        localVarQueryParameter["include_archived"] = includeArchived;
      }

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {PaymentSourceBodyDto} paymentSourceBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentSourcesControllerUpdatePaymentSource: async (
      id: string,
      workspaceId: string,
      paymentSourceBodyDto: PaymentSourceBodyDto,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      assertParamExists(
        "paymentSourcesControllerUpdatePaymentSource",
        "id",
        id,
      );
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "paymentSourcesControllerUpdatePaymentSource",
        "workspaceId",
        workspaceId,
      );
      // verify required parameter 'paymentSourceBodyDto' is not null or undefined
      assertParamExists(
        "paymentSourcesControllerUpdatePaymentSource",
        "paymentSourceBodyDto",
        paymentSourceBodyDto,
      );
      const localVarPath = `/workspaces/{workspaceId}/payment-sources/{id}`
        .replace(`{${"id"}}`, encodeURIComponent(String(id)))
        .replace(`{${"workspaceId"}}`, encodeURIComponent(String(workspaceId)));
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        paymentSourceBodyDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * PaymentSourcesApi - functional programming interface
 * @export
 */
export const PaymentSourcesApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    PaymentSourcesApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async paymentSourcesControllerArchivePaymentSource(
      id: string,
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse20012>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.paymentSourcesControllerArchivePaymentSource(
          id,
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} workspaceId
     * @param {PaymentSourceBodyDto} paymentSourceBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async paymentSourcesControllerCreatePaymentSource(
      workspaceId: string,
      paymentSourceBodyDto: PaymentSourceBodyDto,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse20012>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.paymentSourcesControllerCreatePaymentSource(
          workspaceId,
          paymentSourceBodyDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} workspaceId
     * @param {boolean} [includeArchived]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async paymentSourcesControllerListPaymentSources(
      workspaceId: string,
      includeArchived?: boolean,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<Array<InlineResponse20012>>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.paymentSourcesControllerListPaymentSources(
          workspaceId,
          includeArchived,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {PaymentSourceBodyDto} paymentSourceBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async paymentSourcesControllerUpdatePaymentSource(
      id: string,
      workspaceId: string,
      paymentSourceBodyDto: PaymentSourceBodyDto,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse20012>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.paymentSourcesControllerUpdatePaymentSource(
          id,
          workspaceId,
          paymentSourceBodyDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * PaymentSourcesApi - factory interface
 * @export
 */
export const PaymentSourcesApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = PaymentSourcesApiFp(configuration);
  return {
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentSourcesControllerArchivePaymentSource(
      id: string,
      workspaceId: string,
      options?: any,
    ): AxiosPromise<InlineResponse20012> {
      return localVarFp
        .paymentSourcesControllerArchivePaymentSource(id, workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} workspaceId
     * @param {PaymentSourceBodyDto} paymentSourceBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentSourcesControllerCreatePaymentSource(
      workspaceId: string,
      paymentSourceBodyDto: PaymentSourceBodyDto,
      options?: any,
    ): AxiosPromise<InlineResponse20012> {
      return localVarFp
        .paymentSourcesControllerCreatePaymentSource(
          workspaceId,
          paymentSourceBodyDto,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} workspaceId
     * @param {boolean} [includeArchived]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentSourcesControllerListPaymentSources(
      workspaceId: string,
      includeArchived?: boolean,
      options?: any,
    ): AxiosPromise<Array<InlineResponse20012>> {
      return localVarFp
        .paymentSourcesControllerListPaymentSources(
          workspaceId,
          includeArchived,
          options,
        )
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} id
     * @param {string} workspaceId
     * @param {PaymentSourceBodyDto} paymentSourceBodyDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    paymentSourcesControllerUpdatePaymentSource(
      id: string,
      workspaceId: string,
      paymentSourceBodyDto: PaymentSourceBodyDto,
      options?: any,
    ): AxiosPromise<InlineResponse20012> {
      return localVarFp
        .paymentSourcesControllerUpdatePaymentSource(
          id,
          workspaceId,
          paymentSourceBodyDto,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * PaymentSourcesApi - object-oriented interface
 * @export
 * @class PaymentSourcesApi
 * @extends {BaseAPI}
 */
export class PaymentSourcesApi extends BaseAPI {
  /**
   *
   * @param {string} id
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PaymentSourcesApi
   */
  public paymentSourcesControllerArchivePaymentSource(
    id: string,
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return PaymentSourcesApiFp(this.configuration)
      .paymentSourcesControllerArchivePaymentSource(id, workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} workspaceId
   * @param {PaymentSourceBodyDto} paymentSourceBodyDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PaymentSourcesApi
   */
  public paymentSourcesControllerCreatePaymentSource(
    workspaceId: string,
    paymentSourceBodyDto: PaymentSourceBodyDto,
    options?: AxiosRequestConfig,
  ) {
    return PaymentSourcesApiFp(this.configuration)
      .paymentSourcesControllerCreatePaymentSource(
        workspaceId,
        paymentSourceBodyDto,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} workspaceId
   * @param {boolean} [includeArchived]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PaymentSourcesApi
   */
  public paymentSourcesControllerListPaymentSources(
    workspaceId: string,
    includeArchived?: boolean,
    options?: AxiosRequestConfig,
  ) {
    return PaymentSourcesApiFp(this.configuration)
      .paymentSourcesControllerListPaymentSources(
        workspaceId,
        includeArchived,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} id
   * @param {string} workspaceId
   * @param {PaymentSourceBodyDto} paymentSourceBodyDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PaymentSourcesApi
   */
  public paymentSourcesControllerUpdatePaymentSource(
    id: string,
    workspaceId: string,
    paymentSourceBodyDto: PaymentSourceBodyDto,
    options?: AxiosRequestConfig,
  ) {
    return PaymentSourcesApiFp(this.configuration)
      .paymentSourcesControllerUpdatePaymentSource(
        id,
        workspaceId,
        paymentSourceBodyDto,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
