/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Monqom API
 * The Monqom API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, {
  type AxiosPromise,
  type AxiosInstance,
  type AxiosRequestConfig,
} from "axios";
import type { Configuration } from "../configuration";
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from "../common";
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  type RequestArgs,
  BaseAPI,
  RequiredError,
} from "../base";
// @ts-ignore
import type { InlineResponse2006 } from "../model";
// @ts-ignore
import type { UpdateWorkspaceDto } from "../model";
/**
 * WorkspaceScopedApi - axios parameter creator
 * @export
 */
export const WorkspaceScopedApiAxiosParamCreator = function (
  configuration?: Configuration,
) {
  return {
    /**
     *
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    workspaceScopedControllerGetWorkspace: async (
      workspaceId: string,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "workspaceScopedControllerGetWorkspace",
        "workspaceId",
        workspaceId,
      );
      const localVarPath = `/workspaces/{workspaceId}`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "GET",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
    /**
     *
     * @param {string} workspaceId
     * @param {UpdateWorkspaceDto} updateWorkspaceDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    workspaceScopedControllerUpdateWorkspace: async (
      workspaceId: string,
      updateWorkspaceDto: UpdateWorkspaceDto,
      options: AxiosRequestConfig = {},
    ): Promise<RequestArgs> => {
      // verify required parameter 'workspaceId' is not null or undefined
      assertParamExists(
        "workspaceScopedControllerUpdateWorkspace",
        "workspaceId",
        workspaceId,
      );
      // verify required parameter 'updateWorkspaceDto' is not null or undefined
      assertParamExists(
        "workspaceScopedControllerUpdateWorkspace",
        "updateWorkspaceDto",
        updateWorkspaceDto,
      );
      const localVarPath = `/workspaces/{workspaceId}`.replace(
        `{${"workspaceId"}}`,
        encodeURIComponent(String(workspaceId)),
      );
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: "PUT",
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter["Content-Type"] = "application/json";

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        updateWorkspaceDto,
        localVarRequestOptions,
        configuration,
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * WorkspaceScopedApi - functional programming interface
 * @export
 */
export const WorkspaceScopedApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator =
    WorkspaceScopedApiAxiosParamCreator(configuration);
  return {
    /**
     *
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async workspaceScopedControllerGetWorkspace(
      workspaceId: string,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse2006>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.workspaceScopedControllerGetWorkspace(
          workspaceId,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
    /**
     *
     * @param {string} workspaceId
     * @param {UpdateWorkspaceDto} updateWorkspaceDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async workspaceScopedControllerUpdateWorkspace(
      workspaceId: string,
      updateWorkspaceDto: UpdateWorkspaceDto,
      options?: AxiosRequestConfig,
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string,
      ) => AxiosPromise<InlineResponse2006>
    > {
      const localVarAxiosArgs =
        await localVarAxiosParamCreator.workspaceScopedControllerUpdateWorkspace(
          workspaceId,
          updateWorkspaceDto,
          options,
        );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration,
      );
    },
  };
};

/**
 * WorkspaceScopedApi - factory interface
 * @export
 */
export const WorkspaceScopedApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance,
) {
  const localVarFp = WorkspaceScopedApiFp(configuration);
  return {
    /**
     *
     * @param {string} workspaceId
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    workspaceScopedControllerGetWorkspace(
      workspaceId: string,
      options?: any,
    ): AxiosPromise<InlineResponse2006> {
      return localVarFp
        .workspaceScopedControllerGetWorkspace(workspaceId, options)
        .then((request) => request(axios, basePath));
    },
    /**
     *
     * @param {string} workspaceId
     * @param {UpdateWorkspaceDto} updateWorkspaceDto
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    workspaceScopedControllerUpdateWorkspace(
      workspaceId: string,
      updateWorkspaceDto: UpdateWorkspaceDto,
      options?: any,
    ): AxiosPromise<InlineResponse2006> {
      return localVarFp
        .workspaceScopedControllerUpdateWorkspace(
          workspaceId,
          updateWorkspaceDto,
          options,
        )
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * WorkspaceScopedApi - object-oriented interface
 * @export
 * @class WorkspaceScopedApi
 * @extends {BaseAPI}
 */
export class WorkspaceScopedApi extends BaseAPI {
  /**
   *
   * @param {string} workspaceId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkspaceScopedApi
   */
  public workspaceScopedControllerGetWorkspace(
    workspaceId: string,
    options?: AxiosRequestConfig,
  ) {
    return WorkspaceScopedApiFp(this.configuration)
      .workspaceScopedControllerGetWorkspace(workspaceId, options)
      .then((request) => request(this.axios, this.basePath));
  }

  /**
   *
   * @param {string} workspaceId
   * @param {UpdateWorkspaceDto} updateWorkspaceDto
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof WorkspaceScopedApi
   */
  public workspaceScopedControllerUpdateWorkspace(
    workspaceId: string,
    updateWorkspaceDto: UpdateWorkspaceDto,
    options?: AxiosRequestConfig,
  ) {
    return WorkspaceScopedApiFp(this.configuration)
      .workspaceScopedControllerUpdateWorkspace(
        workspaceId,
        updateWorkspaceDto,
        options,
      )
      .then((request) => request(this.axios, this.basePath));
  }
}
